#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 519167-web-01 52.203.91.47:80 check\n\tserver 519167-web-02 100.26.152.120:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart